version: '3.9'

services:
  db_v2:
    image: mysql:8
    container_name: trading-db-v2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trading_v2
      MYSQL_USER: trading_user
      MYSQL_PASSWORD: trading_password
    ports:
      - "3308:3306"
    volumes:
      - db_data_v2:/var/lib/mysql

  phpmyadmin_v2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-v2
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db_v2
      PMA_USER: trading_user
      PMA_PASSWORD: trading_password

volumes:
  db_data_v2:
